import vue from '@vitejs/plugin-vue';
import alias from '@rollup/plugin-alias';
import uglifyPlugin from 'rollup-plugin-uglify';
import { viteStaticCopy } from 'vite-plugin-static-copy';
import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  plugins: [
    vue(),
    uglifyPlugin.uglify(),
    viteStaticCopy({
      targets: [{ src: 'src/**/*.scss', dest: 'styles/' }],
    }),
    alias({
      entries: [
        {
          find: '@',
          replacement: resolve(__dirname, 'src'),
        },
      ],
    }),
  ],
  build: {
    lib: {
      entry: resolve(__dirname, 'src/index.ts'),
      formats: ['es'],
      name: 'vue-game-starter',
    },
    rollupOptions: {
      external: ['vue'],
      output: {
        exports: 'named',
        globals: {
          vue: 'Vue',
        },
      },
    },
    emptyOutDir: false, // to retain the types folder generated by tsc
  },
  resolve: {
    alias: {
      '~': resolve(__dirname, ''),
    },
  },
});
